# GitHub Actions workflow to run main.py twice daily and save output artifacts
name: Run BLVD Fetcher Twice Daily

on:
  schedule:
    - cron: '0 6,18 * * *'  # At 06:00 and 18:00 UTC every day
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux64/chromedriver-linux64.zip
          unzip /tmp/chromedriver.zip -d /tmp/
          chmod +x /tmp/chromedriver-linux64/chromedriver

      - name: Download Google Chrome
        run: |
          wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y /tmp/chrome.deb || sudo apt-get -f install -y

      - name: Set ChromeDriver path
        run: echo "CHROMEDRIVER_PATH=/tmp/chromedriver-linux64/chromedriver" >> $GITHUB_ENV

      - name: Update chromedriver path in script
        run: |
          sed -i "s|chromedriver_path = .*$|chromedriver_path = '/tmp/chromedriver-linux64/chromedriver'|" main.py

      - name: Run script
        env:
          DISPLAY: :99
        run: |
          python main.py

      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed_1_beds_outputs
          path: |
            processed_1_beds_*.txt
            processed_1_beds_*.csv
